os:
  - osx

language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo g
after_script:
  - git config user.name "droid-Q"
  - git config user.email "droidqw@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/ci_token/${CI_TOKEN}/g" ./_config.yml
  - hexo deploy
branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/droid-Q/droid-Q.github.io.git

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - droidqw@gmail.com
  on_success: change
  on_failure: always