os:
  - osx

language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo g
after_script:
  - git config user.name "droid-Q"
  - git config user.email "droidqw@gmail.com"
  - git clone https://github.com/droid-Q/droid-Q.github.io.git .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i "s/ci_token/${CI_TOKEN}/g" ./_config.yml || exit 1
  - hexo deploy
branches:
  only:
    - master
notifications:
  email:
    - droidqw@gmail.com
  on_success: change
  on_failure: always