os:
  - osx

language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo g
after_script:
  - cd public
  - git init
  - git config user.name "droid-Q"
  - git config user.email "droidqw@gmail.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/droid-Q/droid-Q.github.io.git

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - droidqw@gmail.com
  on_success: change
  on_failure: always