version: 4.0.0
variant: default
logo:
    text: GU.DEV
    logoUrl: /img/favicon.svg
head:
    favicon: /img/favicon.svg
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/droid-Q'
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
search:
    type: insight
comment:
    type: valine
    app_id: 7QmxO6EAkJFokEnGO6ekzag4-MdYXbMMI
    app_key: wL0iIelU4SNNyv1gnVGTq34H
    notify: false
    verify: false
    placeholder: 'Just go go, 支持Markdown~'
    guest_info: 'nick,mail,link,zhangsan'
    pageSize: 10
donates:
    -
        type: alipay
        qrcode: 'https://raw.githubusercontent.com/droid-Q/PicGo/master/20200412224726.jpg'
    -
        type: wechat
        qrcode: 'https://raw.githubusercontent.com/droid-Q/PicGo/master/20200412224846.jpg'
    -
        type: bitcoin
        qrcode: 'https://raw.githubusercontent.com/droid-Q/PicGo/master/20200412224802.jpg'
    -
        type: ethereum
        qrcode: 'https://raw.githubusercontent.com/droid-Q/PicGo/master/20200412224827.jpg'
    -
        type: buymeacoffee
        url: 'https://www.buymeacoffee.com/DJQClvH'
share:
    type: sharejs
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Droid
        author_title: Programming Enthusiast
        location: 'Jiaxing, China'
        avatar: 
        avatar_rounded: false
        gravatar: droidqw@gmail.com
        follow_link: 'https://github.com/droid-Q'
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/droid-Q'
            Facebook:
                icon: fab fa-facebook
                url: 'http://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'http://twitter.com'
            Dribbble:
                icon: fab fa-dribbble
                url: 'http://dribbble.com'
            RSS:
                icon: fas fa-rss
                url: /
    -
        position: left
        type: toc
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
    -
        position: left
        type: subscribe_email
        description: 
        feedburner_id: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    gallery: true
    google_analytics:
        tracking_id: UA-145376170-1
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
